/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:72e39dd5-aec4-4223-a44c-bb7c6fd4ed28",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SYqhspHzz",
    "aws_user_pools_web_client_id": "2qmpl1c8cnkr9t56ld96v3ohj1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ylq4fbxsqffydfwrw3god4g5cu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mrij42twmvg3nnmchrou7rfb4i",
    "API": {
        "endpoints": [
            {
                "name": "StayOnTaskAPIGateway",
                "endpoint": "https://c9wswilgi5.execute-api.us-east-1.amazonaws.com/prod"
            }
        ]
    }
};


export default awsmobile;
